# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Raven < Formula
  desc "Plain markdown notes with custom schemas and annotations for querying"
  homepage "https://github.com/aidanlsb/raven"
  version "0.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/aidanlsb/raven/releases/download/v0.0.1/raven_0.0.1_darwin_x86_64.tar.gz"
      sha256 "1d5d5a9174b421c11a0f52be471edb2d4a67c916a66358053cc58dcb43226d17"

      def install
        bin.install "rvn"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/aidanlsb/raven/releases/download/v0.0.1/raven_0.0.1_darwin_arm64.tar.gz"
      sha256 "ea1feae462c04b975cd4bcc77ab15301b6afd3b743d4942adcd00d057349ec45"

      def install
        bin.install "rvn"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/aidanlsb/raven/releases/download/v0.0.1/raven_0.0.1_linux_x86_64.tar.gz"
      sha256 "d92d0f63a4537496690c0b1daadac547a92773da8bd475224a273bf4b13e6964"
      def install
        bin.install "rvn"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/aidanlsb/raven/releases/download/v0.0.1/raven_0.0.1_linux_arm64.tar.gz"
      sha256 "100bf3bcb64582b6bbc683019ba3f2c54307819c17cb2ffcf082a5df25c7324e"
      def install
        bin.install "rvn"
      end
    end
  end

  test do
    system "#{bin}/rvn", "--help"
  end
end
