# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rvn < Formula
  desc "Plain markdown notes with custom schemas and annotations for querying"
  homepage "https://github.com/aidanlsb/raven"
  version "0.0.9"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/aidanlsb/raven/releases/download/v0.0.9/raven_0.0.9_darwin_x86_64.tar.gz"
      sha256 "0647e2d35157155d6f7154385ec22cf7fec923dc0f428fa6d3191b00272941f7"

      def install
        bin.install "rvn"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/aidanlsb/raven/releases/download/v0.0.9/raven_0.0.9_darwin_arm64.tar.gz"
      sha256 "d45d17f89b1c777117a3c12d2f7cd1be393b23c4e04e58c269c8e4c0ace5802c"

      def install
        bin.install "rvn"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/aidanlsb/raven/releases/download/v0.0.9/raven_0.0.9_linux_x86_64.tar.gz"
      sha256 "65311ebbcdaf085837eb5478b25038a0e167960666512f00b1342cbc8fb215f2"
      def install
        bin.install "rvn"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/aidanlsb/raven/releases/download/v0.0.9/raven_0.0.9_linux_arm64.tar.gz"
      sha256 "ecb0ef63cf71901f0737625f4dae877539673dff695560c5d12f42f4f58fd23d"
      def install
        bin.install "rvn"
      end
    end
  end

  test do
    system "#{bin}/rvn", "--help"
  end
end
