# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rvn < Formula
  desc "Plain markdown notes with custom schemas and annotations for querying"
  homepage "https://github.com/aidanlsb/raven"
  version "0.0.30"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/aidanlsb/raven/releases/download/v0.0.30/raven_0.0.30_darwin_x86_64.tar.gz"
      sha256 "f2f0569e9df52fdc457c8892a81b1b0405cfc720de783cb8573a58bd865f1429"

      def install
        bin.install "rvn"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/aidanlsb/raven/releases/download/v0.0.30/raven_0.0.30_darwin_arm64.tar.gz"
      sha256 "0a8b0590ea305cbbd4208a421f87f81a5456d15d33bdbb6580ae5060a190d25b"

      def install
        bin.install "rvn"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/aidanlsb/raven/releases/download/v0.0.30/raven_0.0.30_linux_x86_64.tar.gz"
      sha256 "0d4bcaed9879026ceef221542b6d56988f259873005e5d32d62e1fab029a4450"
      def install
        bin.install "rvn"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/aidanlsb/raven/releases/download/v0.0.30/raven_0.0.30_linux_arm64.tar.gz"
      sha256 "1029f88f1df8ea14e6f7fa6ebb7b569c36b4890fb9e852a4229393e0e3972ce5"
      def install
        bin.install "rvn"
      end
    end
  end

  test do
    system "#{bin}/rvn", "--help"
  end
end
